from flask import Flask, request, redirect, url_for, render_template_string, session
import sqlite3
from datetime import date

app = Flask(__name__)
app.secret_key = "KITAPHANA_SECRET_2026"
@app.route("/logout") 
def logout(): 
    session.clear() 
    return redirect(url_for("login"))


USERS = {
    "library": {
        "password": "library123",
        "role": "librarian"
    },
    "admin": {
        "password": "admin123",
        "role": "admin"
    }
}
DB_NAME = "kitaphana.db"


# =========================================================
# ДЕРЕКҚОРҒА ҚОСЫЛУ
# =========================================================

import os

DATABASE_URL = os.environ.get("DATABASE_URL")

def get_db():
    if DATABASE_URL:
        import psycopg
        from psycopg.rows import dict_row

        return psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row
        )

    db = sqlite3.connect(DB_NAME)
    db.row_factory = sqlite3.Row
    return db


# =========================================================
# ДЕРЕКҚОРДЫ ҚҰРУ
# =========================================================

def init_db():

    db = get_db()

    if DATABASE_URL:
        id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    else:
        id_type = "INTEGER PRIMARY KEY AUTOINCREMENT"

    # ОҚЫРМАНДАР
    db.execute(f"""
        CREATE TABLE IF NOT EXISTS okuyandar (
            id {id_type},
            aty TEXT NOT NULL,
            synyp TEXT,
            turi TEXT
        )
    """)

    # КІТАПТАР
    db.execute(f"""
        CREATE TABLE IF NOT EXISTS kitaptar (
            id {id_type},
            kitap_id TEXT NOT NULL UNIQUE,
            ataui TEXT NOT NULL,
            avtor TEXT,
            sanat TEXT,
            jalpy_sany INTEGER DEFAULT 0
        )
    """)

    # КІТАП БЕРУ
    db.execute(f"""
        CREATE TABLE IF NOT EXISTS kitap_beru (
            id {id_type},
            kuni TEXT NOT NULL,
            okuyman_id INTEGER NOT NULL,
            kitap_id INTEGER NOT NULL,
            berildi TEXT DEFAULT 'Иә',
            kaitaryldy TEXT DEFAULT 'Жоқ',
            kaitaru_kuni TEXT,
            merzim TEXT
        )
    """)

    db.commit()
    db.close()

# =========================================================
# БАСТЫ БЕТ
# =========================================================
@app.route("/login", methods=["GET", "POST"])
def login():

    error = ""

    if request.method == "POST":

        username = request.form["username"]
        password = request.form["password"]

        user = USERS.get(username)

        if user and user["password"] == password:

            session["username"] = username
            session["role"] = user["role"]

            return redirect(url_for("home"))

        error = "Логин немесе пароль қате"

    return render_template_string("""
    <!DOCTYPE html>
    <html lang="kk">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Кітапханаға кіру</title>

        <style>
            body {
                font-family: Arial, sans-serif;
                background: #f2f4f7;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                margin: 0;
            }

            .login-box {
                background: white;
                width: 90%;
                max-width: 380px;
                padding: 30px;
                border-radius: 15px;
                box-shadow: 0 5px 20px rgba(0,0,0,0.15);
            }

            h2 {
                text-align: center;
                margin-bottom: 25px;
            }

            input {
                width: 100%;
                box-sizing: border-box;
                padding: 12px;
                margin-bottom: 15px;
                border: 1px solid #ccc;
                border-radius: 8px;
                font-size: 16px;
            }

            button {
                width: 100%;
                padding: 12px;
                background: #2563eb;
                color: white;
                border: none;
                border-radius: 8px;
                font-size: 16px;
                cursor: pointer;
            }

            .error {
                color: red;
                text-align: center;
                margin-bottom: 15px;
            }
        </style>
    </head>

    <body>

        <div class="login-box">

            <h2>📚 Мектеп кітапханасы</h2>

            {% if error %}
                <div class="error">{{ error }}</div>
            {% endif %}

            <form method="post">

                <input
                    type="text"
                    name="username"
                    placeholder="Логин"
                    required
                >

                <input
                    type="password"
                    name="password"
                    placeholder="Пароль"
                    required
                >

                <button type="submit">
                    Кіру
                </button>

            </form>

        </div>

    </body>
    </html>
    """)
def is_logged_in():
    return "username" in session


def is_librarian():
    return session.get("role") == "librarian"
   
@app.route("/")
def home():

    if "username" not in session:
        return redirect(url_for("login"))

    db = get_db()

    total_books = db.execute("""
        SELECT COALESCE(SUM(jalpy_sany), 0) AS value
        FROM kitaptar
    """).fetchone()["value"]

    total_readers = db.execute("""
        SELECT COUNT(*) AS value
        FROM okuyandar
    """).fetchone()["value"]

    currently_out = db.execute("""
        SELECT COUNT(*) AS value
        FROM kitap_beru
        WHERE berildi = 'Иә'
          AND kaitaryldy = 'Жоқ'    
    """).fetchone()["value"]

    if DATABASE_URL:
        overdue = db.execute("""
            SELECT COUNT(*) AS value
            FROM kitap_beru
            WHERE berildi = 'Иә'
              AND kaitaryldy = 'Жоқ'
              AND merzim::date < CURRENT_DATE
        """).fetchone()["value"]
    else:
        overdue = db.execute("""
            SELECT COUNT(*)
            FROM kitap_beru
            WHERE berildi = 'Иә'
              AND kaitaryldy = 'Жоқ'
              AND date(merzim) < date('now', 'localtime')
        """).fetchone()[0]

    db.close()

    return render_template_string("""
    <!DOCTYPE html>

    <html lang="kk">

    <head>

        <meta charset="UTF-8">

        <meta name="viewport"
              content="width=device-width, initial-scale=1.0">

        <title>Кітапхана басқару жүйесі</title>

        <style>

            body {
                font-family: Arial, sans-serif;
                background: #f2f4f7;
                margin: 0;
                padding: 20px;
            }

            h1 {
                text-align: center;
                margin-bottom: 30px;
            }

            .cards {
                max-width: 1000px;
                margin: auto;

                display: grid;

                grid-template-columns:
                    repeat(auto-fit, minmax(200px, 1fr));

                gap: 20px;
            }

            .card {
                background: white;

                padding: 25px;

                border-radius: 15px;

                text-align: center;

                box-shadow:
                    0 3px 10px rgba(0,0,0,0.12);
            }

            .card-title {
                font-size: 18px;
            }

            .number {
                font-size: 42px;

                font-weight: bold;

                margin-top: 10px;
            }

            .menu {
                max-width: 1000px;

                margin: 35px auto;

                display: grid;

                grid-template-columns:
                    repeat(auto-fit, minmax(220px, 1fr));

                gap: 15px;
            }

            .button {
                display: block;

                padding: 18px;

                background: #ffffff;

                border-radius: 12px;

                text-align: center;

                text-decoration: none;

                color: #222;

                font-size: 18px;

                font-weight: bold;

                box-shadow:
                    0 2px 8px rgba(0,0,0,0.12);
            }

            .button:hover {
                background: #e9eef5;
            }

            .danger {
                color: #cc0000;
            }

        </style>

    </head>

    <body>

        <h1>КІТАПХАНА БАСҚАРУ ЖҮЙЕСІ</h1>


        <div class="cards">

            <div class="card">

                <div class="card-title">
                    Барлық кітап
                </div>

                <div class="number">
                    {{ total_books }}
                </div>

            </div>


            <div class="card">

                <div class="card-title">
                    Оқырмандар
                </div>

                <div class="number">
                    {{ total_readers }}
                </div>

            </div>


            <div class="card">

                <div class="card-title">
                    Қазір берілген
                </div>

                <div class="number">
                    {{ currently_out }}
                </div>

            </div>


            <div class="card">

                <div class="card-title">
                    Мерзімі өткен
                </div>

                <div class="number danger">
                    {{ overdue }}
                </div>

            </div>

        </div>


        <div class="menu">

            <a class="button"
               href="/readers">
                ОҚЫРМАНДАР
            </a>


            <a class="button"
               href="/books">
                КІТАПТАР
            </a>


            <a class="button"
               href="/loans">
                КІТАП БЕРУ
            </a>


            <a class="button"
               href="/report">
                ЕСЕП
            </a>
            ```html
            <a class="button danger" href="/logout">
                ЖҮЙЕДЕН ШЫҒУ
            </a>
```

        </div>


    </body>

    </html>

    """,
    total_books=total_books,
    total_readers=total_readers,
    currently_out=currently_out,
    overdue=overdue
    )


# =========================================================
# ОҚЫРМАНДАР
# =========================================================

@app.route("/readers")
def readers():

    db = get_db()

    readers = db.execute("""
        SELECT *
        FROM okuyandar
        ORDER BY id DESC
    """).fetchall()

    db.close()

    return render_template_string("""
    <!DOCTYPE html>

    <html lang="kk">

    <head>

        <meta charset="UTF-8">

        <title>Оқырмандар</title>

        <style>

            body {
                font-family: Arial;
                padding: 20px;
                background: #f2f2f2;
            }

            table {
                width: 100%;
                background: white;
                border-collapse: collapse;
            }

            th, td {
                padding: 10px;
                border: 1px solid #ccc;
                text-align: center;
            }

            th {
                background: #eeeeee;
            }

            .add {
                display: inline-block;
                padding: 12px 18px;
                background: white;
                text-decoration: none;
                color: black;
                border-radius: 8px;
                margin-bottom: 20px;
            }

        </style>

    </head>

    <body>

        <h1>ОҚЫРМАНДАР</h1>

        {% if session.get("role") == "librarian" %}
<a class="add"
   href="/readers/add">
    + ОҚЫРМАН ҚОСУ
</a>
{% endif %}

        <table>

            <tr>

                <th>ID</th>
                <th>Аты-жөні</th>
                <th>Сыныбы</th>
                <th>Түрі</th>

            </tr>

            {% for reader in readers %}

            <tr>

                <td>
                    {{ reader["id"] }}
                </td>

                <td>
                    {{ reader["aty"] }}
                </td>

                <td>
                    {{ reader["synyp"] }}
                </td>

                <td>
                    {{ reader["turi"] }}
                </td>

            </tr>

            {% endfor %}

        </table>

        <br>

        <a href="/">
            ← Басты бет
        </a>

    </body>

    </html>
    """, readers=readers)


# =========================================================
# ОҚЫРМАН ҚОСУ
# =========================================================

@app.route("/readers/add", methods=["GET", "POST"])
def add_reader():
    if not is_librarian():
        return "Бұл бөлімге тек кітапханашы кіре алады", 403
    if request.method == "POST":

        aty = request.form["aty"]
        synyp = request.form["synyp"]
        turi = request.form["turi"]

        db = get_db()

        db.execute("""
            INSERT INTO okuyandar
            (
                aty,
                synyp,
                turi
            )
            VALUES (%s, %s, %s)
        """, (
            aty,
            synyp,
            turi
        ))

        db.commit()
        db.close()

        return redirect(url_for("readers"))


    return render_template_string("""
    <!DOCTYPE html>

    <html lang="kk">

    <head>

        <meta charset="UTF-8">

        <title>Оқырман қосу</title>

    </head>

    <body>

        <h1>ОҚЫРМАН ҚОСУ</h1>

        <form method="POST">

            <label>
                Аты-жөні:
            </label>

            <br>

            <input
                type="text"
                name="aty"
                required
            >

            <br><br>


            <label>
                Сыныбы:
            </label>

            <br>

            <input
                type="text"
                name="synyp"
            >

            <br><br>


            <label>
                Түрі:
            </label>

            <br>

            <select name="turi">

                <option value="Оқушы">
                    Оқушы
                </option>

                <option value="Мұғалім">
                    Мұғалім
                </option>

            </select>

            <br><br>

            <button type="submit">
                САҚТАУ
            </button>

        </form>

        <br>

        <a href="/readers">
            ← Оқырмандарға қайту
        </a>

    </body>

    </html>
    """)


# =========================================================
# КІТАПТАР
# =========================================================

@app.route("/books")
def books():

    db = get_db()

    books = db.execute("""
        SELECT
            kitaptar.*,

            (
                SELECT COUNT(*)
                FROM kitap_beru
                WHERE kitap_beru.kitap_id = kitaptar.id
                  AND kitap_beru.kaitaryldy = 'Жоқ'
            ) AS berilgen_sany,

            (
                kitaptar.jalpy_sany -

                (
                    SELECT COUNT(*)
                    FROM kitap_beru
                    WHERE kitap_beru.kitap_id = kitaptar.id
                      AND kitap_beru.kaitaryldy = 'Жоқ'
                )

            ) AS korda_bar

        FROM kitaptar

        ORDER BY kitaptar.id DESC

    """).fetchall()

    db.close()

    return render_template_string("""
    <!DOCTYPE html>

    <html lang="kk">

    <head>

        <meta charset="UTF-8">

        <title>Кітаптар</title>

        <style>

            body {
                font-family: Arial;
                padding: 20px;
                background: #f2f2f2;
            }

            table {
                width: 100%;
                background: white;
                border-collapse: collapse;
            }

            th, td {
                padding: 10px;
                border: 1px solid #ccc;
                text-align: center;
            }

            th {
                background: #eeeeee;
            }

            .add {
                display: inline-block;
                padding: 12px 18px;
                background: white;
                text-decoration: none;
                color: black;
                border-radius: 8px;
                margin-bottom: 20px;
            }

        </style>

    </head>

    <body>

        <h1>КІТАПТАР</h1>

        {% if session.get("role") == "librarian" %}
<a class="add"
   href="/books/add">
    + КІТАП ҚОСУ
</a>
{% endif %}

        <table>

            <tr>

                <th>ID</th>
                <th>Кітап ID</th>
                <th>Атауы</th>
                <th>Автор</th>
                <th>Санаты</th>
                <th>Жалпы саны</th>
                <th>Берілген</th>
                <th>Қолда бар</th>

            </tr>

            {% for book in books %}

            <tr>

                <td>
                    {{ book["id"] }}
                </td>

                <td>
                    {{ book["kitap_id"] }}
                </td>

                <td>
                    {{ book["ataui"] }}
                </td>

                <td>
                    {{ book["avtor"] }}
                </td>

                <td>
                    {{ book["sanat"] }}
                </td>

                <td>
                    {{ book["jalpy_sany"] }}
                </td>

                <td>
                    {{ book["berilgen_sany"] }}
                </td>

                <td>
                    {{ book["korda_bar"] }}
                </td>

            </tr>

            {% endfor %}

        </table>

        <br>

        <a href="/">
            ← Басты бет
        </a>

    </body>

    </html>
    """, books=books)


# =========================================================
# КІТАП ҚОСУ
# =========================================================

@app.route("/books/add", methods=["GET", "POST"])
def add_book():

    if not is_librarian():
        return "Бұл бөлімге тек кітапханашы кіре алады", 403

    db = get_db()

    if request.method == "POST":

        kitap_id = request.form["kitap_id"]
        ataui = request.form["ataui"]
        avtor = request.form["avtor"]
        sanat = request.form["sanat"]
        jalpy_sany = request.form["jalpy_sany"]

        db = get_db()

        db.execute("""
            INSERT INTO kitaptar
            (
                kitap_id,
                ataui,
                avtor,
                sanat,
                jalpy_sany
            )
            VALUES (%s, %s, %s, %s, %s)
        """, (
            kitap_id,
            ataui,
            avtor,
            sanat,
            jalpy_sany
        ))

        db.commit()
        db.close()

        return redirect(url_for("books"))


    return render_template_string("""
    <!DOCTYPE html>

    <html lang="kk">

    <head>

        <meta charset="UTF-8">

        <title>Кітап қосу</title>

    </head>

    <body>

        <h1>КІТАП ҚОСУ</h1>

        <form method="POST">

            <label>
                Кітап ID:
            </label>

            <br>

            <input
                type="text"
                name="kitap_id"
                placeholder="K0001"
                required
            >

            <br><br>


            <label>
                Кітап атауы:
            </label>

            <br>

            <input
                type="text"
                name="ataui"
                required
            >

            <br><br>


            <label>
                Автор:
            </label>

            <br>

            <input
                type="text"
                name="avtor"
            >

            <br><br>


            <label>
                Санаты:
            </label>

            <br>

            <input
                type="text"
                name="sanat"
            >

            <br><br>


            <label>
                Жалпы саны:
            </label>

            <br>

            <input
                type="number"
                name="jalpy_sany"
                value="1"
                min="0"
                required
            >

            <br><br>

            <button type="submit">
                САҚТАУ
            </button>

        </form>

        <br>

        <a href="/books">
            ← Кітаптарға қайту
        </a>

    </body>

    </html>
    """)


# =========================================================
# КІТАП БЕРУ
# =========================================================

@app.route("/loans")
def loans():

    db = get_db()

    loans = db.execute("""
        SELECT
            kitap_beru.*,

            okuyandar.aty AS okuyman_aty,

            kitaptar.ataui AS kitap_atay

        FROM kitap_beru

        JOIN okuyandar
            ON kitap_beru.okuyman_id = okuyandar.id

        JOIN kitaptar
            ON kitap_beru.kitap_id = kitaptar.id

        ORDER BY kitap_beru.id DESC

    """).fetchall()

    db.close()

    return render_template_string("""
    <!DOCTYPE html>

    <html lang="kk">

    <head>

        <meta charset="UTF-8">

        <title>Кітап беру</title>

        <style>

            body {
                font-family: Arial;
                padding: 20px;
                background: #f2f2f2;
            }

           table {
    width: 100%;
    margin: 20px auto;
    background: white;
    border-collapse: collapse;
    table-layout: auto;
}

            th, td {
                padding: 10px;
                border: 1px solid #ccc;
                text-align: center;
            }

            th {
                background: #eeeeee;
            }

            .overdue {
                background: #ffcccc;
                color: #cc0000;
                font-weight: bold;
            }

            .add {
                display: inline-block;
                padding: 12px 18px;
                background: white;
                text-decoration: none;
                color: black;
                border-radius: 8px;
                margin-bottom: 20px;
            }
th, td {
    padding: 10px;
    border: 1px solid #ccc;
    text-align: center;
    white-space: nowrap;
}
        </style>

    </head>

    <body>

        <h1 style="text-align: center;">КІТАП БЕРУ</h1>

        <a class="add"
           href="/loans/add">
           {% if session.get("role") == "librarian" %} <a class="add" href="/loans/add">
+ КІТАП БЕРУ </a>
{% endif %}

<div style="width: 100%; overflow-x: auto;">
        <table>
    <tr>
        <th>ID</th>
        <th>Күні</th>
        <th>Оқырман</th>
        <th>Кітап</th>
        <th>Берілді</th>
        <th>Қайтарылды</th>
        <th>Мерзімі</th>
        {% if session.get("role") == "librarian" %}
            <th>Әрекет</th>
        {% endif %}
    </tr>



            {% for loan in loans %}

            <tr class="
    {% if loan['kaitaryldy'] == 'Жоқ'
          and loan['merzim']
          and loan['merzim'] < today %}
        overdue
    {% endif %}
"> 


                <td>
                    {{ loan["id"] }}
                </td>

                <td>
                    {{ loan["kuni"] }}
                </td>

                <td>
                    {{ loan["okuyman_aty"] }}
                </td>

                <td>
                    {{ loan["kitap_atay"] }}
                </td>

                <td>
                    {{ loan["berildi"] }}
                </td>

                <td>
                    {{ loan["kaitaryldy"] }}
                </td>

                <td>
    {{ loan["merzim"] }}

    {% if session.get("role") == "librarian" %}
        <br><br>
        <a href="/loans/edit/{{ loan['id'] }}">
            Мерзімін өзгерту
        </a>
    {% endif %}
</td>


               {% if session.get("role") == "librarian" %}
<td>
    {% if loan["kaitaryldy"] == "Жоқ" %}
        <form method="POST"
              action="/loans/return/{{ loan['id'] }}">
            <button type="submit">ҚАЙТАРУ</button>
        </form>
    {% else %}
        Қайтарылды
    {% endif %}
</td>
{% endif %}

            </tr>

            {% endfor %}

        </table>
</div>
        <br>

       <div style="text-align: center; margin-top: 20px;">
    <a href="/">
        ← Басты бет
    </a>
</div>

    </body>

    </html>
    """,
    loans=loans,
    today=date.today().isoformat()
    )


# =========================================================
# КІТАПТЫ ҚАЙТАРУ
# =========================================================

@app.route("/loans/return/<int:loan_id>", methods=["POST"])
def return_loan(loan_id):
    if not is_librarian():
        return "Бұл бөлімге тек кітапханашы кіре алады", 403
    db = get_db()

    if DATABASE_URL:
        db.execute("""
            UPDATE kitap_beru
            SET
                kaitaryldy = 'Иә',
                kaitaru_kuni = %s
            WHERE id = %s
        """, (date.today().isoformat(), loan_id))
    else:
        db.execute("""
            UPDATE kitap_beru
            SET
                kaitaryldy = 'Иә',
                kaitaru_kuni = ?
            WHERE id = ?
        """, (date.today().isoformat(), loan_id))

    db.commit()
    db.close()

    return redirect(url_for("loans"))


# =========================================================
# МЕРЗІМДІ ӨЗГЕРТУ
# =========================================================

@app.route("/loans/edit/<int:loan_id>", methods=["GET", "POST"])
def edit_loan(loan_id):

    db = get_db()

    loan = db.execute("""
        SELECT *
        FROM kitap_beru
        WHERE id = %s
    """, (loan_id,)).fetchone()


    if not loan:

        db.close()

        return "Кітап беру жазбасы табылмады"


    if request.method == "POST":

        merzim = request.form["merzim"]

        db.execute("""
            UPDATE kitap_beru

            SET merzim = %s

            WHERE id = %s

        """, (
            merzim,
            loan_id
        ))

        db.commit()
        db.close()

        return redirect(url_for("loans"))


    db.close()


    return render_template_string("""
    <!DOCTYPE html>

    <html lang="kk">

    <head>

        <meta charset="UTF-8">

        <title>Мерзімді өзгерту</title>

    </head>

    <body>

        <h1>МЕРЗІМДІ ӨЗГЕРТУ</h1>


        <form method="POST">

            <label>
                Қайтару мерзімі:
            </label>

            <br><br>

            <input
                type="date"
                name="merzim"
                value="{{ loan['merzim'] }}"
                required
            >

            <br><br>

            <button type="submit">
                САҚТАУ
            </button>

        </form>


        <br>

        <a href="/loans">
            ← Кітап беруге қайту
        </a>

    </body>

    </html>
    """,
    loan=loan
    )


# =========================================================
# КІТАП БЕРУ — ҚОСУ
# =========================================================

@app.route("/loans/add", methods=["GET", "POST"])
def add_loan():
    if not is_librarian():
        return "Бұл бөлімге тек кітапханашы кіре алады", 403
    db = get_db()

    readers = db.execute("""
        SELECT *
        FROM okuyandar
        ORDER BY aty
    """).fetchall()

    books = db.execute("""
        SELECT *
        FROM kitaptar
        ORDER BY ataui
    """).fetchall()

    if request.method == "POST":

        okuyman_id = request.form["okuyman_id"]
        kitap_id = request.form["kitap_id"]
        merzim = request.form["merzim"]

        if DATABASE_URL:
            db.execute("""
                INSERT INTO kitap_beru
                (
                    kuni,
                    okuyman_id,
                    kitap_id,
                    berildi,
                    kaitaryldy,
                    kaitaru_kuni,
                    merzim
                )
                VALUES
                (
                    %s,
                    %s,
                    %s,
                    'Иә',
                    'Жоқ',
                    '',
                    %s
                )
            """, (
                date.today().isoformat(),
                okuyman_id,
                kitap_id,
                merzim
            ))

        else:
            db.execute("""
                INSERT INTO kitap_beru
                (
                    kuni,
                    okuyman_id,
                    kitap_id,
                    berildi,
                    kaitaryldy,
                    kaitaru_kuni,
                    merzim
                )
                VALUES
                (
                    ?,
                    ?,
                    ?,
                    'Иә',
                    'Жоқ',
                    '',
                    ?
                )
            """, (
                date.today().isoformat(),
                okuyman_id,
                kitap_id,
                merzim
            ))

        db.commit()
        db.close()

        return redirect(url_for("loans"))

    db.close()

    return render_template_string("""
    <h2>Кітап беру</h2>

    <form method="post">

        <label>Оқырман:</label>
        <select name="okuyman_id" required>
            {% for reader in readers %}
                <option value="{{ reader.id }}">
                    {{ reader.aty }} — {{ reader.synyp }}
                </option>
            {% endfor %}
        </select>

        <br><br>

        <label>Кітап:</label>
        <select name="kitap_id" required>
            {% for book in books %}
                <option value="{{ book.id }}">
                    {{ book.ataui }}
                </option>
            {% endfor %}
        </select>

        <br><br>

        <label>Мерзімі:</label>
        <input type="date" name="merzim" required>

        <br><br>

        <button type="submit">Кітап беру</button>

    </form>
    """, readers=readers, books=books)
# =========================================================
# ЕСЕП
# =========================================================

@app.route("/report")
def report():

    db = get_db()


    today_issued = db.execute("""
        SELECT COUNT(*) AS value
        FROM kitap_beru
        WHERE kuni::date = CURRENT_DATE
          AND berildi = 'Иә'
    """).fetchone()["value"]


    today_students = db.execute("""
        SELECT COUNT(*) AS value
        FROM kitap_beru
        JOIN okuyandar
          ON kitap_beru.okuyman_id = okuyandar.id
        WHERE kitap_beru.kuni::date = CURRENT_DATE
          AND kitap_beru.berildi = 'Иә'
          AND okuyandar.turi = 'Оқушы'
    """).fetchone()["value"]


    today_teachers = db.execute("""
        SELECT COUNT(*) AS value

        FROM kitap_beru

        JOIN okuyandar
          ON kitap_beru.okuyman_id = okuyandar.id

        WHERE kitap_beru.kuni::date = CURRENT_DATE

          AND kitap_beru.berildi = 'Иә'

          AND okuyandar.turi = 'Мұғалім'

    """).fetchone()["value"]


    currently_out = db.execute("""
        SELECT COUNT(*) AS value

        FROM kitap_beru

        WHERE berildi = 'Иә'

          AND kaitaryldy = 'Жоқ'

    """).fetchone()["value"]


    overdue = db.execute("""
        SELECT COUNT(*) AS value
        FROM kitap_beru
        WHERE berildi = 'Иә'
          AND kaitaryldy = 'Жоқ'
          AND merzim::date < CURRENT_DATE
    """).fetchone()["value"]


    this_month = db.execute("""
        SELECT COUNT(*) AS value
        FROM kitap_beru
        WHERE kuni::date >= DATE_TRUNC('month', CURRENT_DATE)
          AND kuni::date < DATE_TRUNC('month', CURRENT_DATE) + INTERVAL '1 month'
          AND berildi = 'Иә'
    """).fetchone()["value"]

    db.close()


    return render_template_string("""
    <!DOCTYPE html>

    <html lang="kk">

    <head>

        <meta charset="UTF-8">

        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        >

        <title>Есеп</title>


        <style>

            body {

                font-family: Arial, sans-serif;

                background: #f2f2f2;

                padding: 20px;

            }


            h1 {

                text-align: center;

            }


            .cards {

                max-width: 800px;

                margin: 20px auto;

                display: grid;

                grid-template-columns:
                    repeat(
                        auto-fit,
                        minmax(220px, 1fr)
                    );

                gap: 15px;

            }


            .card {

                background: white;

                padding: 25px;

                border-radius: 12px;

                text-align: center;

                box-shadow:
                    0 2px 8px #cccccc;

            }


            .number {

                font-size: 40px;

                font-weight: bold;

                margin-top: 10px;

            }


            .back {

                display: block;

                text-align: center;

                margin: 30px;

                font-size: 18px;

            }


        </style>

    </head>


    <body>


        <h1>
            КІТАПХАНА ЕСЕБІ
        </h1>


        <div class="cards">


            <div class="card">

                <div>
                    Бүгін берілген кітап
                </div>

                <div class="number">
                    {{ today_issued }}
                </div>

            </div>


            <div class="card">

                <div>
                    Бүгін кітап алған оқушылар
                </div>

                <div class="number">
                    {{ today_students }}
                </div>

            </div>


            <div class="card">

                <div>
                    Бүгін кітап алған мұғалімдер
                </div>

                <div class="number">
                    {{ today_teachers }}
                </div>

            </div>


            <div class="card">

                <div>
                    Қазір қолда жоқ кітаптар
                </div>

                <div class="number">
                    {{ currently_out }}
                </div>

            </div>


            <div class="card">

                <div>
                    Мерзімі өтіп кеткен
                </div>

                <div class="number">
                    {{ overdue }}
                </div>

            </div>


            <div class="card">

                <div>
                    Осы айда берілген
                </div>

                <div class="number">
                    {{ this_month }}
                </div>

            </div>


        </div>


        <a class="back"
           href="/">
            ← Басты бетке
        </a>


    </body>

    </html>

    """,
    today_issued=today_issued,
    today_students=today_students,
    today_teachers=today_teachers,
    currently_out=currently_out,
    overdue=overdue,
    this_month=this_month
    )


# =========================================================
# ІСКЕ ҚОСУ
# =========================================================

# Дерекқорды іске қосылған кезде дайындау
init_db()


if __name__ == "__main__":

    app.run(
        host="0.0.0.0",
        port=5000,
        debug=True
    )